# TUN — рекомендуется прописать (даже если включаешь в UI)
tun:
  enable: true
  stack: system # system — обычно лучше на iOS (меньше оверхеда)
  dns-hijack:
    - any:53 # перехват всего DNS
  auto-route: true # автоматическая маршрутизация
  auto-detect-interface: true
# IPv6 — если используешь
ipv6: false
# Оптимизации (экономия батареи, лучше задержки)
unified-delay: true
tcp-concurrent: true
#DNS
dns:
  enable: true
# 1. Сначала узнаем IP самих DoH-серверов через быстрые публичные DNS
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8

  # 2. ОСНОВНОЙ СПИСОК (Сюда идут все запросы первым делом)
  # Используем шифрование, чтобы провайдер не видел, куда мы ходим
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query

  # 3. ЗАПАСНОЙ ВАРИАНТ (Если DoH недоступен или тормозит)
  fallback:
    - system
  # Skip certificate verification to resolve some compatibility issues https://help.nextdns.io/t/g9hdkjz
  skip-cert-verify: true # Для стабильности на iOS (иначе иногда cert-ошибки у NextDNS/AdGuard)
  follow-rule: null # DNS прямые, без прокси — обязательно для iOS/TUN
#  nameserver-policy:
#    '.ru': https://77.88.8.8/dns-query
log-level: silent
allow-lan: true
mixed-port: 7890 # основной порт SOCKS5/HTTP — обязательно!
redir-port: 7891
tproxy-port: 7892
find-process-mode: off
profile: {store-selected: true}
sniffer:
  enable: true
  sniff:
    HTTP:
    TLS:
    # - QUIC               # можно добавить, если нужно
anchors:
  a1: &domain {type: http, format: mrs, behavior: domain, interval: 86400}
  a2: &ipcidr {type: http, format: mrs, behavior: ipcidr, interval: 86400}
  a3: &classical {type: http, format: text, behavior: classical, interval: 86400}
  a4: &inline {type: inline, behavior: classical}

proxies:
  - name: 🇸🇪HostUp
    type: vless
    server: 1.2.3.4
    port: 443
    network: tcp
    udp: true
    tfo: true
    tls: true
    packet-encoding: xudp
    servername: 1.2.3
    client-fingerprint: chrome
    uuid: 123
    flow: 123
    reality-opts:
      public-key: 123
      short-id: 123
  - name: 📋YandexCloud
    type: vless
    server: 5.6.7.8
    port: 443
    network: tcp
    udp: true
    tfo: true
    tls: true
    packet-encoding: xudp
    servername: 1.1.1
    client-fingerprint: chrome
    uuid: 123
    flow: 123
    reality-opts:
      public-key: 123
      short-id: 123

######################################################################################
# Пример подключения С использованием подписки (РАСКОММЕНТИРОВАТЬ ДЛЯ ИСПОЛЬЗОВАНИЯ) #
######################################################################################
#proxy-providers:
#  proxy-sub:
#    type: http
#    url: https://Ваша подписка
#    path: ./proxy-providers/proxy-sub.yml
#    interval: 86400 
#    health-check:
#      enable: true
#      url: https://www.gstatic.com/generate_204
#      interval: 300
#      timeout: 2000
#      lazy: false
#      expected-status: 204
#    override:
#      udp: true
#      tfo: true
proxy-groups:
  - name: Заблок. сервисы
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true
  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/basic-memory.png
    exclude-filter: 🇷🇺
    proxies: [Заблок. сервисы]
  - name: AdReject
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png
    proxies: [REJECT-DROP, REJECT, DIRECT]
  - name: Akamai
    type: select
    icon: https://github.com/homarr-labs/dashboard-icons/raw/main/png/akamai.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Amazon
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Amazon.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Apple
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_1.png
    proxies: [DIRECT]
  - name: Binance
    type: select
    icon: https://upload.wikimedia.org/wikipedia/commons/5/57/Binance_Logo.png
    include-all: true
    proxies: [DIRECT]
  - name: Check_IP
    type: select
    icon: https://github.com/efremych/mrs-rules/raw/main/icons/ip-address.png
    proxies: [DIRECT]
  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/cloudflare.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: DigitalOcean
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/digitalocean.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Google-ads
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/google-shopping.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Hetzner
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/hetzner.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: LinkedIn
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/linkedin.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/main/group-icons/meta.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: MyCustom
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/webtrees.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Oracle
    type: select
    icon: https://github.com/homarr-labs/dashboard-icons/raw/main/png/oracle.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Porn
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub_2.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/main/group-icons/quic.png
    proxies: [REJECT-DROP, REJECT]
  - name: Scaleway
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/scaleway.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Speedtest
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/speedtest.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    exclude-filter: 🇷🇺
    proxies: [Заблок. сервисы, DIRECT]
  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/telegram.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    proxies: [DIRECT, Заблок. сервисы]
  - name: Twitch_HQ
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    proxies: [DIRECT, Заблок. сервисы]
  - name: Vodafone
    type: select
    icon: https://github.com/homarr-labs/dashboard-icons/raw/main/png/vodafone.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: X
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/x.png
    proxies: [Заблок. сервисы, DIRECT]
  - name: Yandex
    type: select
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/yandex.png
    proxies: [DIRECT]
  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    proxies: [Заблок. сервисы, DIRECT]
#https://selfh.st/icons/
rule-providers:
  custom@domain: {!!merge <<: *domain, url: 'https://github.com/efremych/mrs-rules/raw/main/domain/custom.mrs'}
  custom@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/efremych/mrs-rules/raw/main/ip_cidr/custom.mrs'}
  binance@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/binance.mrs'}
  check_ip@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ip-geo-detect.mrs'}
  discord@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/discord.mrs'}
  google-gemini@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google-gemini.mrs'}
  linkedin@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/linkedin.mrs'}
  meta@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/meta.mrs'}
  meta@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/facebook.mrs'}
  openai@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/openai.mrs'}
  porn@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-porn.mrs'}
  speedtest@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/speedtest.mrs'}
  spotify@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/spotify.mrs'}
  telegram@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs'}
  telegram@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/telegram.mrs'}
  twitch@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/twitch.mrs'}
  x@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/x.mrs'}
  youtube@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs'}
  #Белые списки
  yandex@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/yandex.mrs'}
  #Реклама
  adlist@domain: {!!merge <<: *domain, url: 'https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs'}
  exclude_ads@domain: {!!merge <<: *domain, url: 'https://github.com/efremych/mrs-rules/raw/main/domain/exclude_ads.mrs'}
  google-ads@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/google@ads.mrs'}
  #CDN
  akamai@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/akamai.mrs'}
  akamai@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/akamai.mrs'}
  amazon@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/amazon.mrs'}
  amazon@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/amazon.mrs'}
  cloudflare@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/cloudflare.mrs'}
  cloudflare@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/cloudflare.mrs'}
  digitalocean@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/digitalocean.mrs'}
  digitalocean@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/digitalocean@ipcidr.mrs'}
  hetzner@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/hetzner.mrs'}
  hetzner@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/hetzner@ipcidr.mrs'}
  oracle@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/oracle.mrs'}
  oracle@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/PentiumB/CDN-RuleSet/releases/latest/download/oracle.mrs'}
  scaleway@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/scaleway@ipcidr.mrs'}
  vodafone@domain: {!!merge <<: *domain, url: 'https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/vodafone.mrs'}
  vodafone@ipcidr: {!!merge <<: *ipcidr, url: 'https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/vodafone@ipcidr.mrs'}
rules:
  #REJECT
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC,no-track #Блокировка QUIC
  - AND,((RULE-SET,adlist@domain),(NOT,((RULE-SET,exclude_ads@domain)))),AdReject #Блокировка рекламы
  #DIRECT
  - AND,((RULE-SET,check_ip@domain),(NOT,((DOMAIN-SUFFIX, ipinfo.io)))),Check_IP
  - RULE-SET,yandex@domain,Yandex
  #DIRECT_CDN
  - DOMAIN-SUFFIX,icloud.com,Apple #Akamai
  - RULE-SET,binance@domain,Binance #Amazon
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),Twitch_HQ # Разблокировка высокого качества на Twitch.tv (может вызвать рекламу)
  - RULE-SET,twitch@domain,Twitch #Amazon
  #Заблокированные сервисы
  - OR,((RULE-SET,telegram@domain),(RULE-SET,telegram@ipcidr)),Telegram
  - RULE-SET,youtube@domain,YouTube
  - RULE-SET,spotify@domain,Spotify
  - OR,((RULE-SET,meta@domain),(RULE-SET,meta@ipcidr)),Meta
  - RULE-SET,x@domain,X
  - OR,((RULE-SET,google-gemini@domain),(RULE-SET,openai@domain)),AI
  - OR,((RULE-SET,custom@domain),(RULE-SET,custom@ipcidr)),MyCustom
  - RULE-SET,google-ads@domain,Google-ads
  - OR,((RULE-SET,amazon@domain),(RULE-SET,amazon@ipcidr)),Amazon
  - OR,((RULE-SET,akamai@domain),(RULE-SET,akamai@ipcidr)),Akamai
  - OR,((RULE-SET,cloudflare@domain),(RULE-SET,cloudflare@ipcidr)),Cloudflare
  - OR,((RULE-SET,digitalocean@domain),(RULE-SET,digitalocean@ipcidr)),DigitalOcean
  - OR,((RULE-SET,hetzner@domain),(RULE-SET,hetzner@ipcidr)),Hetzner
  - OR,((RULE-SET,oracle@domain),(RULE-SET,oracle@ipcidr)),Oracle
  - RULE-SET,scaleway@ipcidr,Scaleway
  - OR,((RULE-SET,vodafone@domain),(RULE-SET,vodafone@ipcidr)),Vodafone
  - RULE-SET,porn@domain,Porn
  - RULE-SET,linkedin@domain,LinkedIn
  - RULE-SET,speedtest@domain,Speedtest
  - RULE-SET,discord@domain,Discord
  #DIRECT
  - MATCH,DIRECT
